# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sixturtle
email: anurag.sharma@sixturtle.com
description: > # this means to ignore newlines until "baseurl:"
  Sixturtle is a technology consulting company helping organizations build
  next generation cloud based solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sixturtle.com" # the base hostname & protocol for your site
twitter_username: sixturtle
github_username:  sixturtle

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
